### PR TITLE
Remove Grimoire shenanigans

### PR DESCRIPTION
**Pull request by Aizistral**
Since having them available as a separate plugin turns out to be a better option, from now on it will be so: https://github.com/Aizistral-Studios/Grimoire-Shenanigans

### CODE REVIEW

**Comment by EverNife** [comment]
Does this contains all changes from the latests commits?
Or just part of them?

**Comment by Aizistral** [comment]
> Does this contains all changes from the latests commits?
> Or just part of them?

I have left in place a couple changes that aren't directly related to Grimoire.

**Comment by EverNife** [comment]
There was the eclipse part, i remmember now :D

**Comment by Aizistral** [comment]
I have published the FG build with these changes on maven repo: https://github.com/juanmuscaria/maven/commit/bbbb98a1dacd98a7e611c51f7a2b21fa2fc6f9f9
Would have merged this PR myself, but I still have no access here.

**Review by juanmuscaria — APPROVED** [review]
Seems good

**Pull request merged**
